/* Page list for the static router. */
export const registry = [
  {
    "id": "dashboard",
    "source": "dashboard.html",
    "theme": "a",
    "speakerOnly": false,
    "home": "secretariat",
    "sections": [
      "1. Executive Top Header & Alert Banner",
      "Alert Strip",
      "2. Four Top Executive Metric Cards",
      "Card 1",
      "Card 2",
      "Card 3",
      "Card 4",
      "3. Two-Column Operational Core",
      "Left Column (40% / 5 cols): Today's Schedule & Chamber Order",
      "Vertical Timeline List",
      "Item 1: Completed",
      "Item 2: Active / In Progress",
      "Item 3: Confirmed",
      "Item 4: Confirmed",
      "Item 5: Pending",
      "Action / View Roster",
      "Right Column (60% / 7 cols): \"Awaiting Your Decision\" Priority Queue",
      "Priority Card 1 (Urgent Constitutional Ruling)",
      "AI Executive Brief Pill",
      "Inline Actions",
      "Priority Card 2 (Inter-Parliamentary Sanction)",
      "Priority Card 3 (Establishment Promotion)",
      "4. Full-Width Bottom Section: Recent Activity Audit Feed Across All 9 Modules",
      "Filter Tabs Pill Bar",
      "Audit Table Strip",
      "Audit Footer",
      "Inline Interactive Script for Navigation highlight and Panel syncing"
    ]
  },
  {
    "id": "files",
    "source": "files-documents.html",
    "theme": "a",
    "speakerOnly": false,
    "home": null,
    "sections": [
      "Module Strategic Header",
      "Top Action Controls",
      "Three-Panel Split Legislative Workflow Grid",
      "LEFT PANEL: Matters Awaiting Action (28% -> col-span-12 xl:col-span-3)",
      "Quick Search inside Docket Inbox",
      "Filter Chips",
      "Docket List",
      "Item 1: Active Focus Item",
      "Item 2",
      "Item 3",
      "Item 4",
      "Quick Document Registry Stats",
      "CENTER PANEL: Official Document Viewer & AI Executive Brief (44% -> col-span-12 xl:col-span-5)",
      "Docket Overview Bar",
      "AI-Generated Executive Summary Box (Austerity, State Tone)",
      "Extracted Procedural Tags",
      "Rendered Official Document Sheet View (80%+ White, Formal Government Dignity)",
      "Official Archival Watermark Bar",
      "Official Header with Crest",
      "Memo Metadata Header",
      "Paragraphs (Official Parliamentary Draft Style)",
      "Marginal Annotation Box",
      "Official Seal and Digital Security Token Footer",
      "Official Green Coat of Arms Stamp",
      "RIGHT PANEL: AI Precedents, Related Records & Decision Terminal (28% -> col-span-12 xl:col-span-4)",
      "Section A: Related Records & Historical Precedents",
      "Precedent Link 1",
      "Precedent Link 2",
      "Precedent Link 3",
      "Section B: Speaker's Decision & Directive Box",
      "Executive Radio Decisions",
      "Structured Directive Text Area",
      "Urgent Execution Notice",
      "Action Button Row",
      "BOTTOM FULL STRIP: Docket Audit Trail",
      "Stepper Steps",
      "Step 1",
      "Step 2",
      "Step 3",
      "Step 4: Active Current",
      "Persistent Interactive Micro-Script for Terminal Feedback"
    ]
  },
  {
    "id": "directions",
    "source": "directions-decisions.html",
    "theme": "a",
    "speakerOnly": false,
    "home": null,
    "sections": [
      "Top Sovereign Strip / Administrative Control Header",
      "Quick Metrics Strip",
      "Filters and Operational Actions",
      "Search Input",
      "Ministry Filter Dropdown",
      "Date Range Filter",
      "Fast Toggle",
      "Primary Action",
      "Primary Workspace: Kanban Grid + Linked Inspection Drawer",
      "Kanban Columns View (Columns take 8 cols on wide monitors when drawer is active, 12 when hidden)",
      "Column 1: Pending Allocation",
      "Column Header",
      "Card List",
      "Card 1",
      "Card 2",
      "Card Placeholder for Density",
      "Column 2: In-Progress / Under Review (Featured Column)",
      "Active Card (DIR-2024-104)",
      "Progress Bar Representation",
      "Column 3: Completed & Dispatched",
      "Column 4: Overdue / Non-Compliant",
      "Summary Card of Strictures",
      "Right Side Inspection Dossier Drawer (Card #DIR-2024-104 Focus)",
      "Drawer Header Bar",
      "Subject & Metadata Section",
      "Full Directive Text",
      "Linked Source File Document Box",
      "AI Compliance Assessment Engine Box",
      "Compliance Evidence & Upload Zone",
      "Evidence Item 1",
      "Evidence Item 2",
      "Drag-Drop Upload Area",
      "Action Panel Buttons",
      "Persistent Interactive AI Floating Trigger in Bottom Right"
    ]
  },
  {
    "id": "meetings",
    "source": "official-meetings.html",
    "theme": "a",
    "speakerOnly": false,
    "home": null,
    "sections": [
      "Top Sovereign Header Bar",
      "Tab Strip & Filter Controls",
      "TAB 1 CONTENT: Protocol Queue & Conflict Validation",
      "Queue Metric Summary Strip",
      "Queue Dossier Cards List",
      "Card 1: Diplomatic Protocol Tier-1 (Turkiye)",
      "Conflict Status Pill",
      "Purpose & Summary Strip",
      "AI Generated Dossier Card",
      "Action Command Bar",
      "Card 2: Parliamentary Delegation (PRA) with Conflict Warning",
      "Conflict Status Pill: Warning",
      "Card 3: Inter-Provincial Dignitary",
      "Conflict Status Pill: Cleared",
      "TAB 2 CONTENT / COLLAPSIBLE LOWER PANEL: Post-Meeting Minutes & Direct Action Item Converter",
      "Header of Section",
      "AI Transcription Audio Sync Console",
      "Inline Audio Waveform SVG Data-Viz",
      "Key Discussion Highlights",
      "Action Items Extracted by AI Table/Stack",
      "Item 1",
      "Item 2",
      "Persistent Floating AI Assistant Launcher"
    ]
  },
  {
    "id": "schedule",
    "source": "daily-schedule.html",
    "theme": "a",
    "speakerOnly": false,
    "home": null,
    "sections": [
      "Header & Administrative Protocol Controls",
      "View & Date Control Strip",
      "Top-of-Day Executive AI Card",
      "Interactive Conflict Notification Banner (Micro-Interaction)",
      "Operational Week Calendar Grid",
      "Week Grid Container",
      "Col 0: Timestamps",
      "Day Columns (Mon to Sun)",
      "Monday 21",
      "09:00 - 10:30 Internal Briefing",
      "11:00 - 14:00 House Floor",
      "16:00 - 17:30 APNS Committee",
      "Tuesday 22",
      "10:00 - 12:00 Business Advisory",
      "13:00 - 14:30 EU Delegation",
      "15:30 - 17:00 File Approvals",
      "Wednesday 23",
      "10:30 - 13:30 House Sitting",
      "High Priority Constitutional Joint Session (Gold Border) with Interactive Warning Hover",
      "Conflict Warning Tooltip",
      "Thursday 24 (Active / Selected Day)",
      "09:00 - 10:15 SPS Briefing",
      "10:30 - 13:00 Presiding NA",
      "13:15 - 14:15 Turkish Ambassador Luncheon",
      "15:00 - 16:00 Delegation of APNS & PRA",
      "16:30 - 17:30 Chamber File Approvals",
      "18:00 - 19:30 Chief Guest Event",
      "Friday 25",
      "10:00 - 12:30 Friday Chamber Sitting",
      "15:00 - 17:00 Council of Common Interests",
      "Saturday 26",
      "11:00 - 13:00 Constituency Delegations",
      "Sunday 27",
      "Drag & Drop Instruction Subtext",
      "Selected Day Detail Strip: Thursday, 24 October 2024",
      "Official Schedule Table",
      "Row 1",
      "Row 2 (Live / In-Progress)",
      "Row 3",
      "Row 4",
      "Row 5",
      "Row 6",
      "Modal Dialog: Insert Official Chamber Appointment",
      "Persistent Bottom Right Floating AI Assistant Button"
    ]
  },
  {
    "id": "speeches",
    "source": "speeches-engagements.html",
    "theme": "a",
    "speakerOnly": false,
    "home": null,
    "sections": [
      "Official Module Header with Dual Identity & Primary Controls",
      "Action Buttons with strict Institutional Visual Weights",
      "Main Institutional Workspace: 68% Drafting Desk / 32% Intelligence Bank",
      "LEFT COLUMN: Speech Editor & Tour Programme Builder (68% width -> lg:col-span-8)",
      "Speech Editor Panel",
      "Event Header Card",
      "Metadata Ribbon",
      "Teleprompter Delivery Metrics Gauge Bar",
      "Pacing Cadence Visualization",
      "Parliamentary AI Smart First-Draft Advisory Banner",
      "Rich Speech Drafting Desk / Prompter Preview Surface",
      "Text Styling / Teleprompter Formatting Toolbar",
      "Document Workspace Area",
      "Opening Arabic Invocation",
      "Urdu Formal Protocol Greeting",
      "Formal English Address Body",
      "Cue Note Component",
      "Precedent Insertion Marker Container",
      "Speaker Transition Cue",
      "Urdu Concluding Invocations",
      "Teleprompter Settings Drawer Footer",
      "Tab Switcher: Tour Programme Builder & Protocol Manifest",
      "Official Tour Manifest Steps",
      "Item 1",
      "Item 2",
      "Item 3",
      "Item 4",
      "RIGHT COLUMN: Past Speeches Archive & AI Precedent Bank (32% width -> lg:col-span-4)",
      "Search Past Speeches Module",
      "Search Input",
      "Retrieved Past Addresses Cards",
      "Archive Card 1",
      "Archive Card 2",
      "Archive Card 3",
      "AI Quote & Constitutional Citation Suggester",
      "Featured High-Authority Quote Card",
      "Secondary Quote Card",
      "Quick Delivery Teleprompter Display Specs",
      "Teleprompter High-Contrast Modal Simulation Overlay",
      "Micro-Interactions Script"
    ]
  },
  {
    "id": "calls",
    "source": "telephone-log.html",
    "theme": "a",
    "speakerOnly": false,
    "home": null,
    "sections": [
      "Section: Header Bar & Registry Context",
      "Action Group",
      "Administrative Filter Grid",
      "Search Input",
      "Filter: Line",
      "Filter: Priority",
      "Filter: Date Range",
      "Metric Quick Rollout & Sparkline Strip",
      "Main Administrative Call Ledger",
      "Responsive Table Wrapper",
      "Row 1",
      "Row 2",
      "Row 3",
      "Row 4",
      "Row 5",
      "Ledger Pagination & Administrative Verification Footnote",
      "Section: Secondary Grid with Call Statistics & Live Chamber Channel Monitor",
      "Channel Status Card",
      "Official Dispatcher Notice",
      "AI Voice Transcription Summary Widget",
      "Modal / Docked Overlay: New Call Entry & AI Voice Transcription Form",
      "Modal Header",
      "Modal Body Form",
      "Caller Identity Row",
      "Telecommunication Channel & Direction",
      "Direct Recording / Voice Dictation Feature",
      "Voice Transcription Preview Card",
      "Legislative Dossier Cross-Linking",
      "Follow-up Action / Note",
      "Modal Actions",
      "Inline JavaScript for Micro-Interactions & Ledger Filtering"
    ]
  },
  {
    "id": "approvals",
    "source": "remote-approvals.html",
    "theme": "a",
    "speakerOnly": false,
    "home": null,
    "sections": [
      "Persistent High-Security Enclave Bar",
      "Executive Remote Portal Headliner",
      "Live Urgent Count Status Badge",
      "Primary Working Area: 2-Column Split Console",
      "Left Column: Spotlight Active Dossier (7 Cols)",
      "Sovereign Emblem & Official Registry Metadata",
      "Document Meta Subject Banner",
      "AI Constitutional Digest Box",
      "Document Pagination Visualizer / PDF Excerpt",
      "Speaker's Annotation Box (Optional handwritten/typed instruction)",
      "Right Column: Touch-Optimized Decision Deck (5 Cols)",
      "Step 1: Action Selector Heading",
      "Large Touch Action Targets (Min 56px height for touch ergonomics)",
      "Option 1: Selected Positive Action",
      "Option 2: Secretariat Observation",
      "Option 3: Morning Conference Referral",
      "Step 2: Strict Biometric / Cryptographic Confirmation Deck",
      "Warning Notice",
      "Hardware Security Token Indicator",
      "Simulated Key Indicator Pins",
      "Primary Dispatch Call to Action (60px Height for high clarity / no miss)",
      "Speaker Audit Trace Footer",
      "Bottom Row: High-Clarity Queue of Other Remote Pending Files",
      "Queue Card 2",
      "Queue Card 3",
      "Interactive JavaScript Handling Remote Confirmation & Countdown"
    ]
  },
  {
    "id": "press",
    "source": "media-press.html",
    "theme": "a",
    "speakerOnly": false,
    "home": null,
    "sections": [
      "Breadcrumbs & Sovereign Protocol Banner",
      "Live Telemetry & Timestamp",
      "Operational Filter Strip & Action Command",
      "Media Source Filter",
      "Sentiment Filter",
      "Date Period Filter",
      "Quick Toggles",
      "Primary Action Solid Sovereign Green",
      "Metric Summary Strip (Stat Tiles with Sovereign Micro-Visuals)",
      "Stat 1",
      "Stat 2",
      "Sparkline Vector",
      "Stat 3",
      "Flat Sparkline",
      "Stat 4 Flagged / Critical",
      "Operational Core Grid: 60% Feed / 40% Drafting Engine",
      "LEFT COLUMN (60% / 7 Cols): Daily Parliamentary News & Media Digest Feed",
      "Feed Header & Sorter",
      "ITEM 1: CRITICAL FLAGGED",
      "Card Top Bar",
      "Headline & Media Clipping Preview",
      "Legislative Fact-Check Callout Box",
      "Video Broadcast Thumbnail Clip",
      "Action Command Footer",
      "ITEM 2: POSITIVE INSTITUTIONAL COVERAGE",
      "Photo Clip",
      "ITEM 3: NEUTRAL REPORTING",
      "RIGHT COLUMN (40% / 5 Cols): AI-Assisted Press Release Drafting & Statement Console",
      "Console Master Container",
      "Console Sovereign Header",
      "Target Story Context Banner",
      "Drafting Workspace Form",
      "Tone Selector Tabs",
      "Headline Input",
      "AI Draft Editor Body",
      "Distribution Routing Multi-Selector",
      "Action Buttons Bar",
      "Quick Regulatory Reference Dossier Card",
      "Persistent Floating AI Assistant Launcher (Pinned Bottom Right)"
    ]
  },
  {
    "id": "cards",
    "source": "greeting-cards.html",
    "theme": "a",
    "speakerOnly": false,
    "home": null,
    "sections": [
      "Top Occasion Header Bar",
      "Role / View Switcher",
      "Create Campaign Action",
      "Occasion Calendar Strip with Lead-time Badges",
      "Card 1 (Active Campaign)",
      "Card 2",
      "Card 3",
      "Card 4",
      "Two-Panel Console Grid",
      "LEFT PANEL: Recipient Protocol Roster (42% -> 5 cols)",
      "Search & Filters",
      "Protocol Tier Pills",
      "Recipient List",
      "Item 1 (Active/Selected)",
      "Item 2",
      "Item 3",
      "Item 4",
      "Item 5",
      "Batch Selection Counter",
      "RIGHT PANEL: AI-Personalized Card Preview & Editorial Suite (58% -> 7 cols)",
      "Occasion Indicator Banner",
      "Dignified Parchment State Card Preview",
      "Visual Accent Header Band",
      "Crest & National Attribution",
      "Salutation & Addressee",
      "Card Body Content",
      "Urdu Inscription Parallel Text Box",
      "Sign-off & Digital Official Seal",
      "Simulated Signature Placeholder / Crest Stamp",
      "Personal Touch AI Customizer & Options",
      "Bottom Action & Dispatch Bar",
      "Left Summary",
      "Right Action Buttons",
      "Print Parchment Cards",
      "Send via Diplomatic Bag / MoFA",
      "Primary 1-Click Approval Action (52px height)"
    ]
  },
  {
    "id": "desk",
    "source": "speaker-dashboard.html",
    "theme": "b",
    "speakerOnly": false,
    "home": "speaker",
    "sections": [
      "Top Section: Institutional Greeting & State Context",
      "Quick Executive Actions",
      "Institutional Metric Cards (4 Tiles)",
      "Card 1",
      "Card 2",
      "Card 3: Urgency State",
      "Card 4",
      "Two-Column Operations Layout: Left Schedule (40%), Right Decision Deck (60%)",
      "Left Column: Daily Schedule",
      "Vertical Timeline Feed",
      "Event 1 (Completed)",
      "Event 2 (In Progress / Next)",
      "Event 3 (Confirmed)",
      "Event 4 (Confirmed)",
      "Event 5 (Tentative)",
      "Right Column: Awaiting Speaker Decision (Decision Deck)",
      "File Cards Stack",
      "Decision Item 1",
      "AI Summary Box",
      "Action Footbar",
      "Decision Item 2",
      "Decision Item 3",
      "Bottom Section: Official Audit Log / Recent Secretariat Activity Feed",
      "Filter Tabs",
      "Institutional Tabular Log",
      "Row 1",
      "Row 2",
      "Row 3",
      "Row 4"
    ]
  },
  {
    "id": "follow-up",
    "source": "speaker-follow-up-dashboard.html",
    "theme": "b",
    "speakerOnly": true,
    "home": null,
    "sections": [
      "Top Context Navigation Ribbon",
      "Main View Container",
      "Executive Header with Bilinguality & Authority Switch",
      "Executive Compliance Metric Bar",
      "Total Active",
      "On Track",
      "In Progress",
      "Overdue",
      "Verified This Month",
      "Filter & Operational Toolbar",
      "Search bar",
      "Department Filter",
      "Priority Filter",
      "View Switcher",
      "Main Workspace: 4-Column Board + Contextual Review Panel",
      "Kanban 4 Columns Container (8 Cols on XL)",
      "Column 1: Pending Action",
      "Card 1",
      "Card 2",
      "Column 2: In Progress",
      "Card 3",
      "Card 4",
      "Column 3: Overdue / Escalation Required (High Attention)",
      "Card 5 (Selected Card with Drawer Target)",
      "Card 6",
      "Column 4: Completed & Verified",
      "Card 7",
      "Card 8",
      "Integrated Executive Review Drawer (4 Cols on XL)",
      "Review Drawer Header",
      "Subject Overview Card",
      "Formal Speaker Directive Text",
      "Source File Connection",
      "Evidence & Submissions Dropzone / Status",
      "Direct Speaker Actions / Escalation Triggers",
      "Audit Trail Snapshot",
      "Supplementary Compliance Roster Table for Quick Bulk Inspection",
      "Row 1",
      "Row 2",
      "Row 3",
      "Row 4",
      "Row 5",
      "Official Seal & Constitutional Note"
    ]
  },
  {
    "id": "ai",
    "source": "speaker-ai-assistant.html",
    "theme": "b",
    "speakerOnly": true,
    "home": null,
    "sections": [
      "Top Document Header Context Bar",
      "Breadcrumb navigation & file registration index",
      "Institutional Title & Official Urdu Transcript Header",
      "Administrative Utility Button Group",
      "Workspace Canvas",
      "Dual-Pane Working Workspace",
      "LEFT PANE: Official Secretariat Note Sheet (Source Scan View)",
      "Document Action Toolbar",
      "High-fidelity Note Sheet Simulation",
      "Institutional Watermark Background Impression",
      "Official Secretariat Header",
      "Note Content Paragraphs",
      "Formal Closing & Pre-Signature Paragraph",
      "Authentic Departmental Signatures & Minute Trail",
      "Secretary NA Elevation Block",
      "RIGHT PANE: AI-Generated Legislative Brief & Analytical Insights",
      "AI Executive Brief Card",
      "Key Facts Grid",
      "Synthesized Core Points",
      "Precedent & Risk Assessment",
      "Related Parliamentary Records & Prior Decisions",
      "Linked record 1",
      "Linked record 2",
      "PROMINENT SPEAKER'S DECISION & ORDER BOX (حکم جناب اسپیکر)",
      "Box Header with Sovereign Identification",
      "Interactive Decision Selector (Radio Group)",
      "Option 1: Approved as Proposed (Active)",
      "Option 2: Approved with Modifications",
      "Option 3: Returned with Observations",
      "Option 4: Directions for Standing Committee",
      "Option 5: Rejected",
      "Directive Textarea & Speech-to-Text Audio Console",
      "AI Template Presets",
      "Voice-to-Text Dictation Strip",
      "Real-time SVG Audio Waveform Indicator",
      "Action Verification & Issue Bar",
      "Cryptographic Digital Stamp Confirmation Checkbox",
      "Command Execution Action Buttons",
      "Confirmation Toast Feedback Element (Hidden by default)",
      "Institutional Workflow Audit Trail & Verification Chain (سابقہ کارروائی اور تصدیقی ریکارڈ)",
      "Step 1",
      "Step 2",
      "Step 3",
      "Step 4"
    ]
  }
];
